# Adam L. Johnson, M.D. (aljohnson@mgh.harvard.edu)
# Cardiovascular Research Center, Division of Cardiology
# Massachusetts General Hospital

from matplotlib.pyplot import axes
import numpy as np
from scipy.ndimage import label, binary_fill_holes, center_of_mass
import cv2 as cv
from skimage import measure


def get_area_cm2(M: np.ndarray, pixel_spacing_mm: list, tissue_label=1):
    pixel_area_cm2 = np.prod(pixel_spacing_mm) / (10**len(pixel_spacing_mm))
    area_cm2 = (M == tissue_label).sum() * pixel_area_cm2
    return area_cm2


def get_centroid_px(M: np.ndarray, tissue_label=1) -> np.ndarray:
    return np.array(center_of_mass(M, labels=tissue_label))


def get_centroid_cm(M: np.ndarray, pixel_spacing_mm: list, tissue_label=1) -> np.ndarray:
    centroid = get_centroid_px(M, tissue_label=tissue_label)
    centroid[0] *= pixel_spacing_mm[0] / 10
    centroid[1] *= pixel_spacing_mm[1] / 10
    return centroid


def _largest_connected_structure_bool(label_array: np.ndarray, tissue_label) -> np.ndarray:
    """
    Get the larged structure that considers ``tissue_label`` pixels/voxels connected even if they touch diagonally.

    Parameters
    ----------
        label_array (numpy.ndarray):
            Label (e.g. 2d image segmentation)

        tissue_label (int):
            Label to select from the np array

    Returns
    -------
        numpy.ndarray:
        Mask corresponding to the largest connected structure
    """
    labeled_array, num_features = label(
        label_array == tissue_label, structure=np.ones((3,)*len(label_array.shape)))
    max_feature = np.argmax([np.sum(labeled_array == feature)
                            for feature in range(1, num_features+1)]) + 1
    return labeled_array == max_feature


def _contour_sk2cv(c: np.ndarray) -> list:
    """
    Convert skimage contour to OpenCV contour

    Parameters
    ----------
    c : np.ndarray
        Contour generated by skimage.measure.find_contour()

    Returns
    -------
    list
        OpenCV image contour that can be used by cv.contourArea()
    """
    c1 = np.expand_dims(c.astype(np.float32), 1)
    return cv.UMat(c1)


def labels_to_contours(M_label: np.ndarray, tissue_labels: list = [1]) -> dict:
    """
    Convert a 2d labeled segmentation to an array of contour. Each ``contour[i]`` corresponds to a ``tissue_label[i]``. For each tissue label, gets the largest connected contour (by area).

    Uses OpenCV ``findContours()``, as this appears faster than scipy's. See https://stackoverflow.com/questions/40441910/fast-method-to-retrieve-contour-mask-from-a-binary-mask-in-python.

    Parameters
    ----------
    M_label : np.ndarray
        2d labeled segmentation

    tissue_labels : list[int], optional
        Array of tissue labels (integers) from which to generate contours, by default [1]

    Returns
    -------
    dict[int, np.ndarray]
        Dictionary of contours, with keys corresponding to tissue types (integers) and values equal to the contour for that tissue type, which itself is a vector of points
    """
    tissue_contours = {}
    for tissue_label in tissue_labels:
        # choose the largest structure in the mask
        mask = _largest_connected_structure_bool(M_label, tissue_label)
        # fill in any holes in the mask
        mask = binary_fill_holes(mask)
        # get the contours
        contours = measure.find_contours(mask, 0.8)
        # choose the largest one (a little redundant with _largest_connected_structure_bool, but safest)
        max_ind = np.argmax([cv.contourArea(_contour_sk2cv(c))
                            for c in contours])
        tissue_contours[tissue_label] = contours[max_ind]

    return tissue_contours


def rotation_mat_2d(d: float) -> np.ndarray:
    c, s = np.cos(d), np.sin(d)
    return np.array([[c, -s], [s, c]])


def fit_ellipse_px(M_label: np.ndarray, tissue_label=1):
    """
    Same as ``fit_ellipse_cm``, but without the affine transormation (i.e. in original pixel coordinates). Used for plotting.

    Parameters
    ----------
    M_label : np.ndarray
        Input 2D image

    tissue_label : int, optional
        Tissue label to mask by, by default 1

    Returns
    -------
    tuple
        Ellipse parameters in pixel coordinate system (pixels, useful for plotting)

        center_px, axes_px, theta_px
    """
    # fit contour
    contour = labels_to_contours(M_label)[tissue_label]

    # calculate ellipse
    # FYI, OpenCV returns a theta that is clockwise and in the 3rd quadrant. Let's fix that.
    # Also, fitEllipse returns the (width,height) of a rotated rect; we want the (minor,major) axes
    center_px, size_px, theta_px = cv.fitEllipse(_contour_sk2cv(contour))
    center_px = np.array(center_px)
    axes_px = 0.5 * np.array(size_px)
    theta_px = 180 - theta_px

    return center_px, axes_px, theta_px


def fit_ellipse_cm(M_label: np.ndarray, pixel_spacing_mm, tissue_label=1):
    """
    Fit an ellipse to a segmented image, using a specific tissue label. This function uses OpenCV's ``fitEllipse()`` and skimage's ``find_contours()`` under the hood. It returns the center, minor/major axes, and degrees rotation (counter-clockwise) in the centimeter-based coordinate system. If the pixels are square, then these values are simply scalar multiples of the pixel coordinates. However, if the pixels are not square, we have to re-calculate the elliptical parameters under affine transformations of rotation and scaling.

    The general form for an ellipse is X^T M X = 1 where M = [A B; B C]. In polynomial form:

    A x^2 + 2 B x y + C y^2 = 1

    If we make a change of coordinates so that X = S X', then the matrix that describes the ellipse in the new coordinate system is S^T M S. We can then get the eigenvectors and eigenvalues to determine the principal axes.

    Parameters
    ----------
    M_label : np.ndarray
        Input 2D image

    pixel_spacing_mm : np.ndarray
        2-element vector describing row and column pixel sizes in millimeters

    tissue_label : int, optional
        Tissue label to mask by, by default 1

    Returns
    -------
    tuple
        Ellipse parameters in  real coordinate system (centimeters)

        center_cm, axes_cm, theta_cm
    """
    # calculate ellipse
    center_px, axes_px, theta_px = fit_ellipse_px(
        M_label, tissue_label=tissue_label)

    # matrix of quadratic form of ellipse in original coordinates (px):
    M_px = np.diag(np.reciprocal(np.square(axes_px)))

    # apply affine transformation (rotation + scaling)
    #   cm = (T_scl * T_rot) * px
    #   px = (T_scl * T_rot)^-1 * cm
    T_rot = rotation_mat_2d(theta_px * np.pi/180)
    T_scl = np.diag(pixel_spacing_mm) / 10
    T_aff = np.linalg.inv(T_scl @ T_rot)
    M_cm = T_aff.T @ M_px @ T_aff

    # get eigenvectors of transformed matrix, sort by largest first
    eigvals, eigvecs = np.linalg.eig(M_cm)
    sort_idx = eigvals.argsort()[::-1]
    eigvals = eigvals[sort_idx]
    eigvecs = eigvecs[:, sort_idx]

    # eigenvalues correspond to minor/major axes
    axes_cm = np.sqrt(np.reciprocal(eigvals))

    # get new rotation from eigenvecs
    theta_cm = np.arctan(abs(eigvecs[0, 1]/eigvecs[1, 1])) * 180 / np.pi

    # convert center to cm
    center_cm = T_scl @ center_px

    return center_cm, axes_cm, theta_cm


def get_bounding_box_pixels(M: np.ndarray, tissue_label=1):
    M_label = (M == tissue_label)
    rows = np.any(M_label, axis=1)
    cols = np.any(M_label, axis=0)
    try:
        rmin, rmax = np.where(rows)[0][[0, -1]]
        cmin, cmax = np.where(cols)[0][[0, -1]]
    except:
        rmin, rmax = 0, np.size(M_label, axis=0)
        cmin, cmax = 0, np.size(M_label, axis=1)
    return np.array([rmin, rmax]), np.array([cmin, cmax])


def common_bounding_box(M_nifti: np.ndarray, tissue_label=1, margin=0, square=False) -> tuple:
    """
    Loops over the time frames of a 4D nifti label (x,y,0,t) and looks at the 2D slices (x,y) for each time step (t).
    Gets the bounding box of the contour on each slice, and then finds a common bounding box for all the slices.

    Parameters
    ----------
        M_nifti (np.ndarray):
            Input 4D nifti labels

        tissue_label (int):
            Label to select from the nifti

        margin (int, optional):
            Extra pixels to pad the bounding box with. Defaults to 0.

    Returns
    -------
        Tuple[np.ndarray, np.ndarray]: Tuple of Row bounds and Column bounds ((row_min, row_max), (col_min, col_max))
    """
    rbounds = []
    cbounds = []
    num_frames = M_nifti.shape[3]
    for t in range(num_frames):
        rt, ct = get_bounding_box_pixels(
            M_nifti[:, :, 0, t], tissue_label=tissue_label)
        if t == 0:
            rbounds = rt
            cbounds = ct
        else:
            rbounds[0] = min(rbounds[0], rt[0])
            rbounds[1] = max(rbounds[1], rt[1])
            cbounds[0] = min(cbounds[0], ct[0])
            cbounds[1] = max(cbounds[1], ct[1])
    rbounds[0] -= margin
    cbounds[0] -= margin
    rbounds[1] += margin
    cbounds[1] += margin

    if square:
        r_span = rbounds[1] - rbounds[0]
        c_span = cbounds[1] - cbounds[0]
        if r_span > c_span:
            pad = int(np.ceil((r_span - c_span)/2))
            cbounds[0] -= pad
            cbounds[1] += pad
        else:
            pad = int(np.ceil((c_span - r_span)/2))
            rbounds[0] -= pad
            rbounds[1] += pad

    return rbounds, cbounds
